### PR TITLE
#168: Updated eo-runtime version to 0.32.0

### LINKED ISSUE #168: Update the repo to runtime of 0.32 version
Seems pr #162 fails because `memory` object was changed. We need update it manually

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #168 

---

### Detailed summary
- Update `eo-runtime` version from `0.30.0` to `0.32.0` in `pom.xml`
- Modify `text.eo` file:
  - Change `while.` to `@`
  - Change `and.` to `@`
  - Modify `start.lt s-len` to `start.as-int.lt s-len`
  - Modify `start.plus len` to `start.as-int.plus len`
  - Remove `s.slice start len` and replace with `s.slice start.as-int len`
  - Modify `start.write (start.plus 1)` to `start.write (start.as-int.plus 1)`
  - Modify `res` to `res.as-bool`
  - Rename `[substr]` to `ends-with`

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please check

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky LGTM! Thanks

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
