### PR TITLE
Move txt

### PR DESCRIPTION
**Pull request by levBagryansky**
@Graur , please review
I copied txt from objectionary/eo according to 
#6 #7 #8 #9

### CODE REVIEW

**Review by Graur — APPROVED** [review]

**Comment by Graur** [comment]
@levBagryansky Looks good!
@yegor256 please, have a look

**Comment by yegor256** [comment]
@levBagryansky where is `.java` class for `regex.compile`?)

**Comment by levBagryansky** [comment]
@yegor256 ,
Does it look right now?

**Comment by Graur** [comment]
@yegor256 @levBagryansky Something is wrong with workflow checks. They didn't start

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@levBagryansky please, fix all checkstyle violations first

**Comment by levBagryansky** [comment]
@Graur , 
Ok, I will copy `text` for now, not the whole directory

**Review by Graur — CHANGES_REQUESTED** [review]
@levBagryansky please, do any commit to restart github checks

**Comment by levBagryansky** [comment]
@Graur , done

**Review by Graur — CHANGES_REQUESTED** [review]
@levBagryansky Where are the rest of the `.java` files? Why didn't you move them?

**Comment by levBagryansky** [comment]
@Graur , 
Added

**Review by Graur — APPROVED** [review]
@levBagryansky Looks good!

**Comment by Graur** [comment]
@yegor256 please, check again. It looks like all the necessary files have been transferred

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
