### PR TITLE
text.compare implemented on eo

### PR DESCRIPTION
**Pull request by EugeneDar**
https://github.com/objectionary/eo-strings/issues/41

### CODE REVIEW

**Comment by EugeneDar** [comment]
@includealex @OlesiaSub please review

**Comment by includealex** [comment]
@EugeneDar sure

**Review by includealex — APPROVED** [review]
@EugeneDar I like it! @yegor256 please take a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
