### PR TITLE
#170: Updated eo-maven-plugin version to 0.32.0

### LINKED ISSUE #170: Update the repo to maven-plugin of 0.32 version
Seems pr #159 fails because syntax was changed. We need update it manually

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes #170

### CODE REVIEW

**Comment by levBagryansky** [comment]
@maxonfjvipon please check

**Review by maxonfjvipon — APPROVED** [review]
@levBagryansky LGTM! Thanks

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
