### PR TITLE
text.as-float implemented

### PR DESCRIPTION
**Pull request by EugeneDar**

### CODE REVIEW

**Comment by EugeneDar** [comment]
@rultor merge

**Comment by EugeneDar** [comment]
@Graur please, have a look

**Comment by EugeneDar** [comment]
@rultor merge

**Review by Graur — APPROVED** [review]

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@rultor hello

**Comment by Graur** [comment]
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
