### PR TITLE
text.index-of on eo

### PR DESCRIPTION
**Pull request by EugeneDar**
https://github.com/objectionary/eo-strings/issues/65

### CODE REVIEW

**Comment by levBagryansky** [comment]
@EugeneDar sure

**Comment by levBagryansky** [comment]
@EugeneDar looks good! @yegor256 please take a look

**Review by levBagryansky — APPROVED** [review]
@EugeneDar looks good!
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
