### PR TITLE
feat(#136): array -> tuple

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. Rename `array` -> `tuple` 
2. Update `eo` version to `0.29.1`

Closes: #136

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@mximp Could you have a look, please?

**Review by mximp — APPROVED** [review]

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you merge that changes, please? Also, apparently, we have to release a new version of `eo-strings`

**Comment by volodya-lombrozo** [comment]
@yegor256 Reminder

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release a new version of `eo-strings` please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.2.0`

**Pull request merged**
