### PR TITLE
Increased stack size

### PR DESCRIPTION
**Pull request by ivan-egorov42**
Closes: #103

### CODE REVIEW

**Comment by ivan-egorov42** [comment]
@Graur pls, have a look.

**Comment by Graur** [comment]
@EugeneDar please, check

**Review by EugeneDar — APPROVED** [review]
@ivan-egorov42 looks good for me

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
