### PR TITLE
`text.at`

### LINKED ISSUE #10: `text.at` object
According to this: https://github.com/objectionary/eo/issues/979

### PR DESCRIPTION
**Pull request by kerelape**
Closes #10

### CODE REVIEW

**Review by Graur — APPROVED** [review]

**Comment by Graur** [comment]
@yegor256 please, have a look

**Comment by yegor256** [comment]
@kerelape @Graur when we deal with strings, it's better NOT to assume that they contain only English letters. Let's use Russia or some other Unicode. This will make our tests much stronger.

**Comment by Graur** [comment]
@yegor256 I think, @kerelape fixed test. Can you check again, please?

**Review by Graur — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor merge

**Comment by Graur** [comment]
@yegor256 It seems there is no access of this repository in yegor256/objectionary-secrets

**Comment by yegor256** [comment]
@Graur fixed, try again

**Comment by Graur** [comment]
@rultor merge

**Comment by Graur** [comment]
@kerelape Thanks!

**Pull request merged**
