### PR TITLE
move sprintf

### PR DESCRIPTION
**Pull request by levBagryansky**
@Graur , please review
I copied sprintf from eo according to #8

### CODE REVIEW

**Comment by levBagryansky** [comment]
@yegor256 , please look

**Comment by Graur** [comment]
@levBagryansky I have already reviewed your changes and approved them. Why you ask to do it again? I don't see any changes

**Comment by yegor256** [comment]
@rultor merge

**Comment by levBagryansky** [comment]
> @levBagryansky I have already reviewed your changes and approved them. Why you ask to do it again? I don't see any changes
I'm sorry for interrupting, did it by accident

**Pull request merged**
