### PR TITLE
text.contains

### PR DESCRIPTION
**Pull request by EugeneDar**
https://github.com/objectionary/eo-strings/issues/93

### CODE REVIEW

**Comment by EugeneDar** [comment]
@Graur @levBagryansky @mximp please have a look

**Review by levBagryansky — APPROVED** [review]
@EugeneDar Looks good!

**Review by mximp — APPROVED** [review]

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
