### PR TITLE
Add `text.is-alpha`

### LINKED ISSUE #128: text.is-alpha
Let's add a method that returns `TRUE` if all chars are letters.

### PR DESCRIPTION
**Pull request by MikhailLipanin**
closes #128

### CODE REVIEW

**Comment by MikhailLipanin** [comment]
@yegor256 can you have a look pls?

**Comment by yegor256** [comment]
@Graur pls review

**Review by Graur — APPROVED** [review]
@MikhailLipanin Looks good to me, thanks!
@yegor256 Please, have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
