### PR TITLE
regex test simplified

### PR DESCRIPTION
**Pull request by EugeneDar**
https://github.com/objectionary/eo-strings/issues/88

### CODE REVIEW

**Comment by EugeneDar** [comment]
@levBagryansky @Graur please have a look

**Comment by levBagryansky** [comment]
@EugeneDar sure

**Review by levBagryansky — APPROVED** [review]
@EugeneDar nice!

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Review by Graur — APPROVED** [review]

**Comment by EugeneDar** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
