### PR TITLE
set failOnWarning flag to true and updated EO version

### PR DESCRIPTION
**Pull request by Graur**
#114

What's done:

- set failOnWarning flag to true 
- updated EO version to latest

### CODE REVIEW

**Comment by Graur** [comment]
@EugeneDar Please, have a look

**Review by EugeneDar — APPROVED** [review]
@Graur looks good.

@yegor256 please, have a look.

**Comment by Graur** [comment]
@yegor256 Can you please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
